# Generated by Django 3.1b1 on 2021-05-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='type',
            new_name='code_type',
        ),
    ]
