# Generated by Django 3.1b1 on 2021-06-13 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tobi', '0003_auto_20210602_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='lang_logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
